SELECT NAME, DATETIME
FROM (SELECT I.NAME, I.DATETIME
        FROM ANIMAL_INS I, ANIMAL_OUTS O
        WHERE 1=1
            AND I.ANIMAL_ID = O.ANIMAL_ID(+)
            AND O.ANIMAL_ID IS NULL
        ORDER BY I.DATETIME ASC)
WHERE ROWNUM <= 3;

