-- 코드를 입력하세요
SELECT p.PRODUCT_ID, p.PRODUCT_NAME, p.PRICE * a.AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT p,
    (
        SELECT PRODUCT_ID, SUM(AMOUNT) as AMOUNT
        FROM FOOD_ORDER
        WHERE TO_CHAR(PRODUCE_DATE, 'YYYYMM') = '202205'
        GROUP BY PRODUCT_ID
    ) a
WHERE p.PRODUCT_ID = a.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, p.PRODUCT_ID ASC