SELECT p.MEMBER_NAME, r.REVIEW_TEXT, TO_CHAR(r.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE 
FROM MEMBER_PROFILE p, REST_REVIEW r
WHERE 1 = 1 
    AND p.MEMBER_ID = r.MEMBER_ID
    AND p.MEMBER_ID IN (
        SELECT MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        HAVING COUNT(MEMBER_ID) = (
            SELECT MAX(COUNT(MEMBER_ID))
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
        )    
    )
ORDER BY r.REVIEW_DATE ASC, r.REVIEW_TEXT ASC;